---
-
  hosts: localhost
  gather_facts: False
  vars:
    - ilo_ip: 172.20.24.212
    - ilo_username: sysadmin
    - ilo_password: C10ud_SHM!
  tasks:
    - name: test hpe ilo
      community.general.hpilo_boot:
        host: "{{ ilo_ip }}"
        login: "{{ ilo_username }}"
        password: "{{ ilo_password }}"
        state: connect
        media: cdrom
        image: http://172.20.22.118:8080/esxi_214.iso
      delegate_to: localhost
    - name: add esxi to the vcenter
      vmware_host:
        hostname: 172.20.22.120
        username: "m.shoaei@vsphere.local"
        password: "Admin@313"
        datacenter_name: "SHM Datacenter"
        esxi_hostname: "172.20.22.212"
        esxi_username: "root"
        esxi_password: "myp@ssw0rd"
        validate_password: False
        state: present
      delegate_to: localhost
...
