---
-
  hosts: localhost
  gather_facts: False
  vars:
    - ilo_ip: 172.20.24.212
    - ilo_username: "ilo_username"
    - ilo_password: "ilo_password"
  tasks:
    - name: test hpe ilo
      community.general.hpilo_boot:
        host: "{{ ilo_ip }}"
        login: "{{ ilo_username }}"
        password: "{{ ilo_password }}"
        state: connect
        media: cdrom
        image: http://"http_ip":"http_port"/esxi_214.iso
      delegate_to: localhost
    - name: add esxi to the vcenter
      vmware_host:
        hostname: "vcenter_IP/vcenter_hostname"
        username: "vcneter_username@vsphere.local"
        password: "vcenter_password"
        datacenter: "datacenter_name"
        folder: '/"datacenter_name"/host'
        #cluster: "cluster_name" 
        esxi_hostname: "172.20.22.212"
        esxi_username: "root"
        esxi_password: "esxi_password"
        validate_certs: False
        state: present
      delegate_to: localhost
...
